<?php 
class IndexController extends Zend_Controller_Action
{
    public function init()
    {
        $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){
            $this->redirect('/login');
        }
        $this->_helper->layout->setLayout('layout_admin');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
//        $model = new Model_Test;
//        $model->test();
        var_dump('bc');
//        $front = Zend_Controller_Front::getInstance();
//        $front->dispatch();
//        try {
//            $front->dispatch();
//        } catch (Exception $e) {
//            echo "<pre>";
//            var_dump($e);
//        }
    }

    public function abcAction()
    {

    }
}